### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mass85** [raymond-lam/priority-q#10]
It appears that priority-q is not capable of handling 500k objects each containing a few strings, because calling `filter()`, `findIndex()`, `new PriorityQ(bigArray, comparer)` ends up with exception `RangeError: Maximum call stack size exceeded`. This is caused by internal usage of spread syntax (i.e. `this.enqueue(...init)`) and `clone()`.

**Comment by raymond-lam** [comment]
@mass85 Great catch. Fixing this right away, and will issue a bug-fix release.

**Comment by raymond-lam** [comment]
Closed via PR #11

**Comment by raymond-lam** [comment]
@mass85 v3.0.2 has been release. Thanks again for reporting this bug!
